// İstanbul Üniversiteleri Listesi
export const ISTANBUL_UNIVERSITIES = [
  "Boğaziçi Üniversitesi",
  "İstanbul Teknik Üniversitesi (İTÜ)",
  "İstanbul Üniversitesi",
  "Marmara Üniversitesi",
  "Yıldız Teknik Üniversitesi (YTÜ)",
  "Sabancı Üniversitesi",
  "Koç Üniversitesi",
  "Galatasaray Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Beykent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "Maltepe Üniversitesi",
  "Özyeğin Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Altınbaş Üniversitesi",
  "Bezmialem Vakıf Üniversitesi",
  "Biruni Üniversitesi",
  "Doğuş Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Gedik Üniversitesi",
  "Haliç Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilim Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Şehir Üniversitesi",
  "İstanbul Topkapı Üniversitesi",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "Kadir Has Üniversitesi",
  "Mef Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Piri Reis Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Diğer",
].sort((a, b) => {
  if (a === 'Diğer') return 1;
  if (b === 'Diğer') return -1;
  return a.localeCompare(b, 'tr-TR');
});

export const UNIVERSITY_YEARS = [
  "Hazırlık",
  "1. Sınıf",
  "2. Sınıf",
  "3. Sınıf",
  "4. Sınıf",
  "5. Sınıf",
  "6. Sınıf",
  "Yüksek Lisans",
  "Doktora",
];

export const DAYS_OF_WEEK = [
  "Pazar",
  "Pazartesi",
  "Salı",
  "Çarşamba",
  "Perşembe",
  "Cuma",
  "Cumartesi",
];

// Üniversite Bölümleri
export const DEPARTMENTS = [
  // Mühendislik
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Endüstri Mühendisliği",
  "Kimya Mühendisliği",
  "Biyomedikal Mühendisliği",
  "Çevre Mühendisliği",
  "Uçak ve Uzay Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
  "Kontrol ve Otomasyon Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Tekstil Mühendisliği",
  "Petrol ve Doğalgaz Mühendisliği",
  "Maden Mühendisliği",
  "Jeoloji Mühendisliği",
  "Gıda Mühendisliği",
  // Sağlık
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Sağlık Yönetimi",
  "Ebelik",
  "Audiometry (Odyoloji)",
  // Hukuk & Sosyal Bilimler
  "Hukuk",
  "Siyaset Bilimi ve Uluslararası İlişkiler",
  "Sosyoloji",
  "Psikoloji",
  "Felsefe",
  "Tarih",
  "Coğrafya",
  "Türk Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "Alman Dili ve Edebiyatı",
  "Fransız Dili ve Edebiyatı",
  "Arap Dili ve Edebiyatı",
  "Mütercim-Tercümanlık",
  // Ekonomi & İşletme
  "İktisat",
  "İşletme",
  "Uluslararası İlişkiler",
  "Uluslararası Ticaret ve Lojistik",
  "Maliye",
  "Bankacılık ve Finans",
  "Muhasebe ve Finansman",
  "Yönetim Bilişim Sistemleri",
  "Ekonometri",
  // Eğitim
  "İlköğretim Matematik Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Türkçe Öğretmenliği",
  "İngilizce Öğretmenliği",
  "Okul Öncesi Öğretmenliği",
  "Sınıf Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Beden Eğitimi ve Spor Öğretmenliği",
  // Mimarlık & Tasarım
  "Mimarlık",
  "İç Mimarlık",
  "Endüstriyel Tasarım",
  "Grafik Tasarım",
  "Peyzaj Mimarlığı",
  "Moda Tasarımı",
  "Tekstil ve Moda Tasarımı",
  // İletişim
  "Gazetecilik",
  "Radyo, Televizyon ve Sinema",
  "Halkla İlişkiler ve Tanıtım",
  "Yeni Medya ve İletişim",
  "Reklamcılık",
  // Fen Bilimleri
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Moleküler Biyoloji ve Genetik",
  "İstatistik",
  "Astronomi ve Uzay Bilimleri",
  // Diğer
  "Turizm İşletmeciliği",
  "Gastronomi ve Mutfak Sanatları",
  "Sosyal Hizmet",
  "Çocuk Gelişimi",
  "Spor Bilimleri",
  "Rekreasyon",
  "Müzik",
  "Güzel Sanatlar",
  "Sinema ve Televizyon",
  "Tiyatro",
  "Fotoğrafçılık",
  "Diğer",
].sort((a, b) => {
  if (a === 'Diğer') return 1;
  if (b === 'Diğer') return -1;
  return a.localeCompare(b, 'tr-TR');
});

export const EVENT_CATEGORIES = [
  { label: 'Maç', value: 'match', icon: 'football' },
  { label: 'Gezi', value: 'trip', icon: 'bus' },
  { label: 'Kamp', value: 'camp', icon: 'bonfire' },
  { label: 'Atölye', value: 'workshop', icon: 'hammer' },
  { label: 'Sohbet/Ders', value: 'talk', icon: 'megaphone' },
  { label: 'Diğer', value: 'other', icon: 'star' },
];
